import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'pt-BR' | 'en-US' | 'es-ES';
type Currency = 'BRL' | 'USD' | 'EUR';
type ThemeMode = 'light' | 'dark' | 'auto';

interface PreferencesContextType {
  language: Language;
  currency: Currency;
  themeMode: ThemeMode;
  isDark: boolean;
  showBalances: boolean;
  setLanguage: (lang: Language) => void;
  setCurrency: (curr: Currency) => void;
  setThemeMode: (mode: ThemeMode) => void;
  setShowBalances: (show: boolean) => void;
  formatCurrency: (value: number) => string;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  'pt-BR': {
    'dashboard': 'Dashboard',
    'transactions': 'Transações',
    'goals': 'Metas',
    'investments': 'Investimentos',
    'reports': 'Relatórios',
    'wallets': 'Carteiras',
    'settings': 'Configurações',
    'patrimony': 'Patrimônio total',
    'revenue_month': 'Receitas (mês)',
    'savings_rate': 'Taxa de Poupança',
    'fixed_commitments': 'Custos Fixos',
    'goals_progress': 'Progresso de Metas',
    'expenses_month': 'Despesas (mês)',
    'balance_month': 'Saldo do mês',
    'recent_transactions': 'Últimas transações',
    'see_all': 'Ver todas',
    'new': 'Novo',
    'save': 'Salvar',
    'edit': 'Editar',
    'cancel': 'Cancelar',
    'delete': 'Excluir',
    'income': 'Receita',
    'expense': 'Despesa',
    'search': 'Buscar...',
    'filter': 'Filtrar',
    'profile': 'Perfil',
    'security': 'Segurança',
    'notifications': 'Notificações',
    'preferences': 'Preferências',
    'logout': 'Sair',
    'manage_profile': 'Gerencie seus dados pessoais',
    'security_sub': 'Senha e proteção',
    'cloud_backup': 'Nuvem e Backup',
    'cloud_sub': 'Status de sincronização',
    'notif_sub': 'Alertas e avisos',
    'pref_sub': 'Idioma, moeda e exibição',
    'syncing': 'Sincronizando...',
    'cloud_synced': 'Nuvem Sincronizada',
    'sync_sub': 'Atualizando com segurança',
    'ready_for_you': 'Tudo pronto para você',
    'end_session': 'Encerrar Sessão',
    'edit_profile': 'Editar Perfil',
    'display_name': 'Nome de Exibição',
    'click_to_change_photo': 'Clique para alterar foto',
    'security_account': 'Segurança e Conta',
    'login_info': 'Informações de Login',
    'verified': 'Verificado',
    'creation_date': 'Criação da conta',
    'last_access': 'Último acesso',
    'password_access': 'Senha e Acesso',
    'password_reset_info': 'Caso deseje alterar sua senha, enviaremos um link para seu e-mail.',
    'send_reset_email': 'Enviar E-mail de Redefinição',
    'push_notifications': 'Notificações Push',
    'email_notifications': 'Notificações por E-mail',
    'app_language': 'Idioma do Aplicativo',
    'default_currency': 'Moeda Padrão',
    'display_mode': 'Modo de Exibição',
    'light': 'Claro',
    'dark': 'Escuro',
    'system': 'Sistema',
    'total_balance': 'Saldo Total',
    'add_transaction': 'Adicionar Transação',
    'category': 'Categoria',
    'description': 'Descrição',
    'value': 'Valor',
    'date': 'Data',
    'confirm': 'Confirmar',
    'close': 'Fechar',
    'cloud_save': 'Salvamento na Nuvem',
    'cloud_save_sub': 'Seus dados estão seguros',
    'cloud_save_desc': 'Utilizamos a tecnologia Google Firebase para garantir que cada lançamento seja salvo instantaneamente.',
    'encryption': 'Criptografia de Ponta',
    'encryption_desc': 'Seus dados trafegam por canais seguros SSL/TLS.',
    'auto_backup': 'Backup Automático',
    'auto_backup_desc': 'Cópias de segurança são criadas a cada alteração.',
    'multi_device': 'Multi-dispositivo',
    'multi_device_desc': 'Acesse de qualquer computador ou celular.',
    'version': 'Versão',
    'cash_flow': 'Fluxo de Caixa',
    'by_category': 'Por Categoria',
    'last_4_weeks': 'Últimas 4 semanas',
    'month_short': 'm',
    'year_short': 'a',
    'search_transactions': 'Buscar lançamentos...',
    'all_months': 'Todos os meses',
    'selected_count': 'selecionados',
    'change_type': 'Trocar Tipo',
    'change_category': 'Trocar Categoria',
    'none_found': 'Nenhum resultado encontrado',
    'confirm_delete': 'Confirmar Exclusão',
    'confirm_delete_msg': 'Tem certeza que deseja excluir este item?',
    'confirm_delete_bulk': 'Tem certeza que deseja excluir {{count}} itens selecionados?',
    'finance_management': 'Gestão Financeira',
    'investment_aporte': 'Aporte',
    'week': 'Sem',
    'import_csv': 'Importar CSV',
    'export_csv': 'Exportar CSV',
    'new_goal': 'Nova Meta',
    'new_asset': 'Novo Ativo',
    'new_wallet': 'Nova Carteira',
    'new_transaction': 'Lançamento',
    'goals_sub': 'Seus objetivos financeiros',
    'investments_sub': 'Sua carteira de ativos',
    'reports_sub': 'Visão consolidada',
    'wallets_sub': 'Selecione ou gerencie suas carteiras',
    'settings_sub': 'Configurações de conta e segurança',
    'dashboard_short': 'Início',
    'add_short': 'Lançar',
    'assets_short': 'Ativos',
    'menu': 'Menu',
    'no_goals_yet': 'Nenhuma meta ainda. Crie sua primeira!',
    'days_remaining': 'dias restantes',
    'deadline_over': 'Prazo encerrado',
    'of': 'de',
    'remaining': 'faltam',
    'distribution': 'Distribuição',
    'summary': 'Resumo',
    'current_patrimony': 'Patrimônio Atual',
    'total_profit': 'Lucro Total',
    'appreciation': 'Valorização',
    'total_invested': 'Total Investido',
    'no_investments_yet': 'Nenhum investimento cadastrado.',
    'units': 'un.',
    'total_income': 'Total Receitas',
    'total_expense': 'Total Despesas',
    'net_worth': 'Patrimônio Líquido',
    'equity_evolution': 'Evolução Patrimonial',
    'expense_ranking': 'Ranking de Despesas',
    'no_expenses_recorded': 'Nenhuma despesa registrada.',
    'full_name': 'Nome Completo',
    'cpf': 'CPF',
    'business_name': 'Razão Social',
    'cnpj': 'CNPJ',
    'selected_caps': 'SELECIONADA',
    'personal': 'Pessoal',
    'business': 'Empresarial',
    'smart_finance_management': 'Gestão Financeira Inteligente',
    'create_account': 'Criar conta',
    'email': 'E-mail',
    'password': 'Senha',
    'or': 'ou',
    'have_account': 'Já tem uma conta? Entre',
    'no_account': 'Não tem uma conta? Crie agora',
    'protected_by': 'Protegido por Firebase e Segurança AI Studio',
    'invalid_credentials': 'E-mail ou senha incorretos.',
    'email_in_use': 'Este e-mail já está em uso. Tente fazer login ou recupere sua senha.',
    'weak_password': 'A senha deve ter pelo menos 6 caracteres.',
    'invalid_email_err': 'O endereço de e-mail não é válido.',
    'connection_error': 'Erro de conexão. Verifique sua internet.',
    'too_many_requests': 'Muitas tentativas malsucedidas. Tente novamente mais tarde.',
    'generic_error': 'Ocorreu um erro ao processar sua solicitação. Tente novamente.',
    'login_hint': 'Tente abrir o app em uma nova aba se o problema persistir.',
    'popup_blocked_err': 'Popup bloqueado. Por favor, permita popups ou abra o app em uma nova aba.',
    'google_error': 'Erro ao entrar com Google.',
    'apple_error': 'Erro ao entrar com Apple.',
    'transaction_type': 'Tipo de Transação',
    'invest': 'Investir',
    'target_value': 'Valor Alvo',
    'already_saved': 'Já Guardado',
    'deadline': 'Prazo',
    'color': 'Cor',
    'asset': 'Ativo',
    'type': 'Tipo',
    'contribution_date': 'Data do Aporte',
    'total_value': 'Valor Total',
    'quantity': 'Quantidade',
    'average_price': 'Preço Médio',
    'delete_now': 'Excluir Agora',
    'cannot_be_undone': 'Esta ação não pode ser desfeita.',
    'wallet_name': 'Nome da Carteira',
    'wallet_name_required': 'O nome da carteira é obrigatório.',
    'cnpj_razao_required': 'CNPJ e Razão Social são obrigatórios.',
    'optional_note': 'Observação (opcional)',
    'details_placeholder': 'Detalhes...',
    'notes_placeholder': 'Notas sobre esta carteira...',
    'edit_transaction': 'Editar Lançamento',
    'new_transaction_modal': 'Novo Lançamento',
    'edit_goal': 'Editar Meta',
    'new_goal_modal': 'Nova Meta',
    'edit_investment': 'Editar Investimento',
    'new_investment_modal': 'Novo Investimento',
    'edit_wallet': 'Editar Carteira',
    'new_wallet_modal': 'Nova Carteira',
    'placeholder_emergency_fund': 'Ex: Fundo de emergência...',
    'placeholder_description_modal': 'Ex: Salário, Mercado...',
    'placeholder_asset': 'Ex: PETR4, AAPL...',
    'placeholder_wallet': 'Ex: Principal, Empresa X...',
    'green': 'Verde',
    'light_green': 'Verde claro',
    'purple': 'Roxo',
    'orange': 'Laranja',
    'red_color': 'Vermelho',
    'stocks': 'Ações',
    'fiis': 'FIIs',
    'treasury': 'Tesouro',
    'crypto': 'Cripto',
    'fixed_income': 'Renda Fixa',
    'salary': 'Salário',
    'freelance': 'Freelance',
    'rent_received': 'Aluguel recebido',
    'investments_cat': 'Investimentos',
    'gift': 'Presente',
    'others': 'Outros',
    'food': 'Alimentação',
    'housing': 'Moradia',
    'transport': 'Transporte',
    'health': 'Saúde',
    'gym': 'Academia',
    'leisure': 'Lazer',
    'education': 'Educação',
    'clothing': 'Vestuário',
    'services': 'Serviços',
    'subscriptions': 'Assinaturas',
    'extras': 'Extras',
    'etfs': 'ETFs',
    'savings': 'Poupança',
    'other_assets': 'Outros ativos',
    'updated': 'Atualizado',
    'saved': 'Salvo',
    'created': 'Criada',
    'added': 'Adicionado',
    'wallet_updated': 'Carteira atualizada',
    'wallet_created': 'Carteira criada',
    'wallet_deleted': 'Carteira removida',
    'transaction_deleted': 'Lançamento removido',
    'goal_deleted': 'Meta removida',
    'investment_deleted': 'Investimento removido',
    'bulk_deleted': 'lançamentos removidos',
    'wallet_changed': 'Carteira alterada',
    'min_wallet_warning': 'Você precisa ter pelo menos uma carteira.',
    'default_wallet_name': 'Minha Carteira',
    'default_wallet_desc': 'Minha conta principal',
    'default_wallet_created': 'Carteira padrão criada',
     'import_success': 'transações importadas!',
    'export_success': 'CSV exportado!',
    'select_file': 'Selecionar Arquivo',
    'click_or_drag_csv': 'Clique aqui ou arraste o arquivo CSV',
    'supported_formats': 'Formatos suportados: .csv',
    'categorizing_ai': 'Categorizando transações com IA...',
    'csv_date': 'Data',
    'csv_description': 'Descrição',
    'csv_value': 'Valor',
    'csv_back': 'Voltar e trocar arquivo',
    'imported_via_csv': 'Importado via CSV',
    'csv_transaction_fallback': 'Transação',
    'unnamed_user': 'Usuário',
    'at_least_one_wallet': 'Você precisa ter pelo menos uma carteira.',
    'wallet': 'Carteira',
    'custom': 'Personalizado',
    'ready': 'Pronto',
    'pref_footer': 'As alterações de tema são aplicadas instantaneamente ao salvar.',
    'forgot_password': 'Esqueceu a senha?',
    'back_to_login': 'Voltar para o login',
    'logout_confirm': 'Deseja encerrar sua sessão?',
    'logout_confirm_desc': 'Você precisará entrar novamente para acessar seus dados.',
    'reset_email_sent': 'E-mail de redefinição enviado! Verifique sua caixa de entrada.',
    'reset_email_err': 'Erro ao enviar e-mail. Tente novamente mais tarde.',
    'yes': 'Sim',
    'no': 'Não',
    'saving': 'Salvando...',
    'sending': 'Enviando...',
    'security_footer_info': 'Sua conta está protegida pelo Firebase Security. As comunicações são criptografadas e o acesso é autenticado seguindo padrões globais de segurança.',
    'push_notif_sub': 'Receba alertas sobre metas e vencimentos no seu dispositivo.',
    'email_notif_sub': 'Relatórios semanais e alertas importantes no seu e-mail.',
    'notif_tip': 'Você pode silenciar notificações individuais nas configurações de cada carteira.',
    'all': 'Tudo',
    'incomes': 'Receitas',
    'expenses': 'Despesas',
    'monthly_yield': 'Rentabilidade Mensal',
    'yield_calculation_info': 'Ao alterar, o valor total será ajustado proporcionalmente.',
    'planning': 'Planejamento',
    'shopping_list': 'Lista de Compras',
    'fixed_expenses': 'Gastos Fixos',
    'add_item': 'Adicionar Item',
    'priority': 'Prioridade',
    'low': 'Baixa',
    'medium': 'Média',
    'high': 'Alta',
    'committed_salary': 'Salário Comprometido',
    'total_fixed': 'Total Fixo',
    'due_day': 'Dia de Vencimento',
    'estimated_price': 'Preço Estimado',
    'total_estimated': 'Total Estimado',
    'planning_desc': 'Organize seu futuro financeiro e compromissos mensais.',
    'income_basis': 'Baseado em ganhos mensais:',
    'high_commitment_warning': 'Atenção: Grande parte da sua renda está comprometida.',
    'item_name': 'Item...',
    'price_short': 'R$',
    'no_items': 'Sua lista de compras está vazia.',
    'expense_name': 'Nome',
    'day_short': 'DIA',
    'fixed_recurrent': 'Recorrência Mensal',
    'no_fixed_expenses': 'Nenhuma despesa fixa cadastrada.',
    'short_warning': 'Alto!',
    'delete_selected': 'Excluir selecionados',
    'cancel_selection': 'Cancelar seleção',
    'complete_registration': 'Termine seu cadastro',
    'verify_account': 'Verifique sua conta',
    'account_verified': 'Conta verificada',
    'birth_date': 'Data de Nascimento',
    'gender': 'Gênero',
    'city': 'Cidade',
    'select': 'Selecionar',
    'male': 'Masculino',
    'female': 'Feminino',
    'other': 'Outro',
    'prefer_not_to_say': 'Prefiro não dizer',
    'city_placeholder': 'Ex: São Paulo',
    'country': 'País',
    'country_placeholder': 'Ex: Brasil',
    'monthly_income': 'Rendimento Mensal',
    'income_info_desc': 'Usado para cálculos de planejamento financeiro.'
  },
  'en-US': {
    'dashboard': 'Dashboard',
    'transactions': 'Transactions',
    'goals': 'Goals',
    'investments': 'Investments',
    'reports': 'Reports',
    'wallets': 'Wallets',
    'settings': 'Settings',
    'patrimony': 'Total Net Worth',
    'revenue_month': 'Revenue (month)',
    'savings_rate': 'Savings Rate',
    'fixed_commitments': 'Fixed Overhead',
    'goals_progress': 'Goals Progress',
    'expenses_month': 'Expenses (month)',
    'balance_month': 'Month Balance',
    'recent_transactions': 'Recent Transactions',
    'see_all': 'See All',
    'new': 'New',
    'save': 'Save',
    'edit': 'Edit',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'income': 'Income',
    'expense': 'Expense',
    'search': 'Search...',
    'filter': 'Filter',
    'profile': 'Profile',
    'security': 'Security',
    'notifications': 'Notifications',
    'preferences': 'Preferences',
    'logout': 'Logout',
    'manage_profile': 'Manage your personal data',
    'security_sub': 'Password and protection',
    'cloud_backup': 'Cloud and Backup',
    'cloud_sub': 'Sync status',
    'notif_sub': 'Alerts and warnings',
    'pref_sub': 'Language, currency and display',
    'syncing': 'Syncing...',
    'cloud_synced': 'Cloud Synced',
    'sync_sub': 'Updating securely',
    'ready_for_you': 'Everything ready for you',
    'end_session': 'Sign Out',
    'edit_profile': 'Edit Profile',
    'display_name': 'Display Name',
    'click_to_change_photo': 'Click to change photo',
    'security_account': 'Security and Account',
    'login_info': 'Login Information',
    'verified': 'Verified',
    'creation_date': 'Account creation',
    'last_access': 'Last access',
    'password_access': 'Password and Access',
    'password_reset_info': 'If you wish to change your password, we will send a link to your email.',
    'send_reset_email': 'Send Reset Email',
    'push_notifications': 'Push Notifications',
    'email_notifications': 'Email Notifications',
    'app_language': 'App Language',
    'default_currency': 'Default Currency',
    'display_mode': 'Display Mode',
    'light': 'Light',
    'dark': 'Dark',
    'system': 'System',
    'total_balance': 'Total Balance',
    'add_transaction': 'Add Transaction',
    'category': 'Category',
    'description': 'Description',
    'value': 'Value',
    'date': 'Date',
    'confirm': 'Confirm',
    'close': 'Close',
    'cloud_save': 'Cloud Storage',
    'cloud_save_sub': 'Your data is safe',
    'cloud_save_desc': 'We use Google Firebase technology to ensure each entry is instantly saved.',
    'encryption': 'Point-to-Point Encryption',
    'encryption_desc': 'Your data travels through secure SSL/TLS channels.',
    'auto_backup': 'Automatic Backup',
    'auto_backup_desc': 'Backups are created with every change.',
    'multi_device': 'Multi-device',
    'multi_device_desc': 'Access from any computer or mobile device.',
    'version': 'Version',
    'cash_flow': 'Cash Flow',
    'by_category': 'By Category',
    'last_4_weeks': 'Last 4 weeks',
    'month_short': 'm',
    'year_short': 'y',
    'search_transactions': 'Search transactions...',
    'all_months': 'All months',
    'selected_count': 'selected',
    'change_type': 'Change Type',
    'change_category': 'Change Category',
    'none_found': 'No results found',
    'confirm_delete': 'Confirm Delete',
    'confirm_delete_msg': 'Are you sure you want to delete this item?',
    'confirm_delete_bulk': 'Are you sure you want to delete {{count}} selected items?',
    'finance_management': 'Financial Management',
    'investment_aporte': 'Contribution',
    'week': 'Week',
    'import_csv': 'Import CSV',
    'export_csv': 'Export CSV',
    'new_goal': 'New Goal',
    'new_asset': 'New Asset',
    'new_wallet': 'New Wallet',
    'new_transaction': 'Transaction',
    'goals_sub': 'Your financial goals',
    'investments_sub': 'Your asset portfolio',
    'reports_sub': 'Consolidated view',
    'wallets_sub': 'Select or manage your wallets',
    'settings_sub': 'Account and security settings',
    'dashboard_short': 'Home',
    'add_short': 'Add',
    'assets_short': 'Assets',
    'menu': 'Menu',
    'no_goals_yet': 'No goals yet. Create your first one!',
    'days_remaining': 'days left',
    'deadline_over': 'Deadline passed',
    'of': 'of',
    'remaining': 'remaining',
    'distribution': 'Distribution',
    'summary': 'Summary',
    'current_patrimony': 'Current Patrimony',
    'total_profit': 'Total Profit',
    'appreciation': 'Appreciation',
    'total_invested': 'Total Invested',
    'no_investments_yet': 'No investments registered yet.',
    'units': 'units',
    'total_income': 'Total Income',
    'total_expense': 'Total Expense',
    'net_worth': 'Net Worth',
    'equity_evolution': 'Equity Evolution',
    'expense_ranking': 'Expense Ranking',
    'no_expenses_recorded': 'No expenses recorded.',
    'full_name': 'Full Name',
    'cpf': 'SSN/ID',
    'business_name': 'Business Name',
    'cnpj': 'Tax ID',
    'selected_caps': 'SELECTED',
    'personal': 'Personal',
    'business': 'Business',
    'smart_finance_management': 'Smart Financial Management',
    'create_account': 'Create account',
    'email': 'Email',
    'password': 'Password',
    'or': 'or',
    'have_account': 'Already have an account? Sign in',
    'no_account': 'No account? Create one now',
    'protected_by': 'Protected by Firebase and AI Studio Security',
    'invalid_credentials': 'Incorrect email or password.',
    'email_in_use': 'This email is already in use. Try signing in or reset your password.',
    'weak_password': 'Password must be at least 6 characters long.',
    'invalid_email_err': 'The email address is not valid.',
    'connection_error': 'Connection error. Check your internet.',
    'too_many_requests': 'Too many unsuccessful attempts. Try again later.',
    'generic_error': 'An error occurred while processing your request. Try again.',
    'login_hint': 'Try opening the app in a new tab if the problem persists.',
    'popup_blocked_err': 'Popup blocked. Please allow popups or open the app in a new tab.',
    'google_error': 'Error signing in with Google.',
    'apple_error': 'Error signing in with Apple.',
    'transaction_type': 'Transaction Type',
    'invest': 'Invest',
    'target_value': 'Target Value',
    'already_saved': 'Already Saved',
    'deadline': 'Deadline',
    'color': 'Color',
    'asset': 'Asset',
    'type': 'Type',
    'contribution_date': 'Contribution Date',
    'total_value': 'Total Value',
    'quantity': 'Quantity',
    'average_price': 'Average Price',
    'delete_now': 'Delete Now',
    'cannot_be_undone': 'This action cannot be undone.',
    'wallet_name': 'Wallet Name',
    'wallet_name_required': 'Wallet name is required.',
    'cnpj_razao_required': 'Tax ID and Business Name are required.',
    'optional_note': 'Note (optional)',
    'details_placeholder': 'Details...',
    'notes_placeholder': 'Notes about this wallet...',
    'edit_transaction': 'Edit Transaction',
    'new_transaction_modal': 'New Transaction',
    'edit_goal': 'Edit Goal',
    'new_goal_modal': 'New Goal',
    'edit_investment': 'Edit Investment',
    'new_investment_modal': 'New Investment',
    'edit_wallet': 'Edit Wallet',
    'new_wallet_modal': 'New Wallet',
    'placeholder_emergency_fund': 'e.g., Emergency fund...',
    'placeholder_description_modal': 'e.g., Salary, Groceries...',
    'placeholder_asset': 'e.g., AAPL, BTC...',
    'placeholder_wallet': 'e.g., Main, Business...',
    'green': 'Green',
    'light_green': 'Light Green',
    'purple': 'Purple',
    'orange': 'Orange',
    'red_color': 'Red',
    'stocks': 'Stocks',
    'fiis': 'REITs',
    'treasury': 'Treasury',
    'crypto': 'Crypto',
    'fixed_income': 'Fixed Income',
    'salary': 'Salary',
    'freelance': 'Freelance',
    'rent_received': 'Rent Received',
    'investments_cat': 'Investments',
    'gift': 'Gift',
    'others': 'Others',
    'food': 'Food',
    'housing': 'Housing',
    'transport': 'Transport',
    'health': 'Health',
    'gym': 'Gym',
    'leisure': 'Leisure',
    'education': 'Education',
    'clothing': 'Clothing',
    'services': 'Services',
    'subscriptions': 'Subscriptions',
    'extras': 'Extras',
    'etfs': 'ETFs',
    'savings': 'Savings',
    'other_assets': 'Other assets',
    'updated': 'Updated',
    'saved': 'Saved',
    'created': 'Created',
    'added': 'Added',
    'wallet_updated': 'Wallet updated',
    'wallet_created': 'Wallet created',
    'wallet_deleted': 'Wallet removed',
    'transaction_deleted': 'Transaction removed',
    'goal_deleted': 'Goal removed',
    'investment_deleted': 'Investment removed',
    'bulk_deleted': 'transactions removed',
    'wallet_changed': 'Wallet changed',
    'min_wallet_warning': 'You must have at least one wallet.',
    'default_wallet_name': 'My Wallet',
    'default_wallet_desc': 'My main account',
    'default_wallet_created': 'Default wallet created',
    'import_success': 'transactions imported!',
    'export_success': 'CSV exported!',
    'select_file': 'Select File',
    'click_or_drag_csv': 'Click here or drag CSV file',
    'supported_formats': 'Supported formats: .csv',
    'categorizing_ai': 'Categorizing transactions with AI...',
    'csv_date': 'Date',
    'csv_description': 'Description',
    'csv_value': 'Value',
    'csv_back': 'Go back and change file',
    'imported_via_csv': 'Imported via CSV',
    'csv_transaction_fallback': 'Transaction',
    'unnamed_user': 'User',
    'at_least_one_wallet': 'You need at least one wallet.',
    'wallet': 'Wallet',
    'custom': 'Custom',
    'ready': 'Ready',
    'pref_footer': 'Theme changes are applied instantly upon saving.',
    'forgot_password': 'Forgot password?',
    'back_to_login': 'Back to login',
    'logout_confirm': 'Do you want to sign out?',
    'logout_confirm_desc': 'You will need to sign in again to access your data.',
    'reset_email_sent': 'Password reset email sent! Check your inbox.',
    'reset_email_err': 'Error sending email. Try again later.',
    'yes': 'Yes',
    'no': 'No',
    'saving': 'Saving...',
    'sending': 'Sending...',
    'security_footer_info': 'Your account is protected by Firebase Security. Communications are encrypted and access is authenticated following global security standards.',
    'push_notif_sub': 'Get alerts about goals and deadlines on your device.',
    'email_notif_sub': 'Weekly reports and important alerts in your email.',
    'notif_tip': 'You can silence individual notifications in each wallet settings.',
    'all': 'All',
    'incomes': 'Incomes',
    'expenses': 'Expenses',
    'monthly_yield': 'Monthly Yield',
    'yield_calculation_info': 'When changing, the total value will be adjusted proportionally.',
    'planning': 'Planning',
    'shopping_list': 'Shopping List',
    'fixed_expenses': 'Fixed Expenses',
    'add_item': 'Add Item',
    'priority': 'Priority',
    'low': 'Low',
    'medium': 'Medium',
    'high': 'High',
    'committed_salary': 'Committed Salary',
    'total_fixed': 'Total Fixed',
    'due_day': 'Due Day',
    'estimated_price': 'Estimated Price',
    'total_estimated': 'Estimated Total',
    'planning_desc': 'Organize your financial future and monthly commitments.',
    'income_basis': 'Based on monthly earnings:',
    'high_commitment_warning': 'Attention: A large part of your income is committed.',
    'item_name': 'Item...',
    'price_short': '$',
    'no_items': 'Your shopping list is empty.',
    'expense_name': 'Name',
    'day_short': 'DAY',
    'fixed_recurrent': 'Monthly Recurrence',
    'no_fixed_expenses': 'No fixed expenses registered.',
    'short_warning': 'High!',
    'delete_selected': 'Delete selected',
    'cancel_selection': 'Cancel selection',
    'complete_registration': 'Complete your registration',
    'verify_account': 'Verify your account',
    'account_verified': 'Account verified',
    'birth_date': 'Birth Date',
    'gender': 'Gender',
    'city': 'City',
    'select': 'Select',
    'male': 'Male',
    'female': 'Female',
    'other': 'Other',
    'prefer_not_to_say': 'Prefer not to say',
    'city_placeholder': 'e.g., New York',
    'country': 'Country',
    'country_placeholder': 'e.g., USA',
    'monthly_income': 'Monthly Income',
    'income_info_desc': 'Used for financial planning calculations.'
  },
  'es-ES': {
    'dashboard': 'Panel',
    'transactions': 'Transacciones',
    'goals': 'Metas',
    'investments': 'Inversiones',
    'reports': 'Reportes',
    'wallets': 'Carteras',
    'settings': 'Ajustes',
    'patrimony': 'Patrimonio total',
    'revenue_month': 'Ingresos (mes)',
    'savings_rate': 'Tasa de Ahorro',
    'fixed_commitments': 'Gastos Fijos',
    'goals_progress': 'Progreso de Metas',
    'expenses_month': 'Gastos (mes)',
    'balance_month': 'Saldo del mes',
    'recent_transactions': 'Últimas transacciones',
    'see_all': 'Ver todo',
    'new': 'Nuevo',
    'save': 'Guardar',
    'edit': 'Editar',
    'cancel': 'Cancelar',
    'delete': 'Eliminar',
    'income': 'Ingreso',
    'expense': 'Gasto',
    'search': 'Buscar...',
    'filter': 'Filtrar',
    'profile': 'Perfil',
    'security': 'Seguridad',
    'notifications': 'Notificaciones',
    'preferences': 'Preferencias',
    'logout': 'Salir',
    'manage_profile': 'Gestione sus datos personales',
    'security_sub': 'Contraseña y protección',
    'cloud_backup': 'Nube y Backup',
    'cloud_sub': 'Estado de sincronización',
    'notif_sub': 'Alertas y avisos',
    'pref_sub': 'Idioma, moneda y visualización',
    'syncing': 'Sincronizando...',
    'cloud_synced': 'Nube Sincronizada',
    'sync_sub': 'Actualizando con seguridad',
    'ready_for_you': 'Todo listo para ti',
    'end_session': 'Cerrar Sesión',
    'edit_profile': 'Editar Perfil',
    'display_name': 'Nombre de Pantalla',
    'click_to_change_photo': 'Haz clic para cambiar foto',
    'security_account': 'Seguridad y Cuenta',
    'login_info': 'Información de Inicio de Sesión',
    'verified': 'Verificado',
    'creation_date': 'Creación de la cuenta',
    'last_access': 'Último acceso',
    'password_access': 'Contraseña y Acceso',
    'password_reset_info': 'Si desea cambiar su contraseña, le enviaremos un enlace a su correo.',
    'send_reset_email': 'Enviar Correo de Restablecimiento',
    'push_notifications': 'Notificaciones Push',
    'email_notifications': 'Notificaciones por Correo',
    'app_language': 'Idioma de la Aplicación',
    'default_currency': 'Moneda Predeterminada',
    'display_mode': 'Modo de Visualización',
    'light': 'Claro',
    'dark': 'Oscuro',
    'system': 'Sistema',
    'total_balance': 'Saldo Total',
    'add_transaction': 'Añadir Transacción',
    'category': 'Categoría',
    'description': 'Descripción',
    'value': 'Valor',
    'date': 'Fecha',
    'confirm': 'Confirmar',
    'close': 'Cerrar',
    'cloud_save': 'Almacenamiento en la Nube',
    'cloud_save_sub': 'Tus datos están seguros',
    'cloud_save_desc': 'Utilizamos la tecnologia Google Firebase para garantizar que cada entrada se guarde al instante.',
    'encryption': 'Cifrado de Extremo a Extremo',
    'encryption_desc': 'Tus datos viajan por canales seguros SSL/TLS.',
    'auto_backup': 'Copia de Seguridad Automática',
    'auto_backup_desc': 'Se crean copias de seguridad con cada cambio.',
    'multi_device': 'Multidispositivo',
    'multi_device_desc': 'Accede desde cualquier ordenador o móvil.',
    'version': 'Versión',
    'cash_flow': 'Flujo de Caja',
    'by_category': 'Por Categoría',
    'last_4_weeks': 'Últimas 4 semanas',
    'month_short': 'm',
    'year_short': 'a',
    'search_transactions': 'Buscar transacciones...',
    'all_months': 'Todos los meses',
    'selected_count': 'seleccionados',
    'change_type': 'Cambiar Tipo',
    'change_category': 'Cambiar Categoría',
    'none_found': 'No se encontraron resultados',
    'confirm_delete': 'Confirmar Eliminación',
    'confirm_delete_msg': '¿Estás seguro de que quieres eliminar este elemento?',
    'confirm_delete_bulk': '¿Estás seguro de que quieres eliminar {{count}} elementos seleccionados?',
    'finance_management': 'Gestión Financiera',
    'investment_aporte': 'Aporte',
    'week': 'Sem',
    'import_csv': 'Importar CSV',
    'export_csv': 'Exportar CSV',
    'new_goal': 'Nueva Meta',
    'new_asset': 'Nuevo Activo',
    'new_wallet': 'Nueva Cartera',
    'new_transaction': 'Transacción',
    'goals_sub': 'Tus objetivos financieros',
    'investments_sub': 'Tu cartera de activos',
    'reports_sub': 'Vista consolidada',
    'wallets_sub': 'Selecciona o gestiona tus carteras',
    'settings_sub': 'Configuración de cuenta y seguridad',
    'dashboard_short': 'Inicio',
    'add_short': 'Añadir',
    'assets_short': 'Activos',
    'menu': 'Menú',
    'no_goals_yet': 'Aún no hay metas. ¡Crea la primera!',
    'days_remaining': 'días restantes',
    'deadline_over': 'Plazo finalizado',
    'of': 'de',
    'remaining': 'faltan',
    'distribution': 'Distribución',
    'summary': 'Resumen',
    'current_patrimony': 'Patrimonio Actual',
    'total_profit': 'Beneficio Total',
    'appreciation': 'Valorización',
    'total_invested': 'Total Invertido',
    'no_investments_yet': 'Ninguna inversión registrada.',
    'units': 'un.',
    'total_income': 'Total de Ingresos',
    'total_expense': 'Total de Gastos',
    'net_worth': 'Patrimonio Neto',
    'equity_evolution': 'Evolución Patrimonial',
    'expense_ranking': 'Ranking de Gastos',
    'no_expenses_recorded': 'Ningún gasto registrado.',
    'full_name': 'Nombre Completo',
    'cpf': 'DNI/CPF',
    'business_name': 'Nombre de la Empresa',
    'cnpj': 'CIF/CNPJ',
    'selected_caps': 'SELECCIONADA',
    'personal': 'Personal',
    'business': 'Empresarial',
    'smart_finance_management': 'Gestión Financiera Inteligente',
    'create_account': 'Crear cuenta',
    'email': 'Email',
    'password': 'Contraseña',
    'or': 'o',
    'have_account': '¿Ya tienes una cuenta? Entrar',
    'no_account': '¿No tienes una cuenta? Crea una ahora',
    'protected_by': 'Protegido por Firebase y Seguridad de AI Studio',
    'invalid_credentials': 'Correo o contraseña incorrectos.',
    'email_in_use': 'Este correo ya está en uso. Intenta iniciar sesión o recupera tu contraseña.',
    'weak_password': 'La contraseña debe tener al menos 6 caracteres.',
    'invalid_email_err': 'La dirección de correo no es válida.',
    'connection_error': 'Error de conexión. Comprueba tu internet.',
    'too_many_requests': 'Demasiados intentos fallidos. Inténtalo más tarde.',
    'generic_error': 'Ocurrió un error al procesar tu solicitud. Inténtalo de nuevo.',
    'login_hint': 'Intenta abrir la aplicación en una nueva pestaña si el problema persiste.',
    'popup_blocked_err': 'Popup bloqueado. Por favor, permite los popups o abre la aplicación en una nueva pestaña.',
    'google_error': 'Error al entrar con Google.',
    'apple_error': 'Error al entrar con Apple.',
    'transaction_type': 'Tipo de Transacción',
    'invest': 'Invertir',
    'target_value': 'Valor Objetivo',
    'already_saved': 'Ya Guardado',
    'deadline': 'Plazo',
    'color': 'Color',
    'asset': 'Activo',
    'type': 'Tipo',
    'contribution_date': 'Fecha del Aporte',
    'total_value': 'Valor Total',
    'quantity': 'Cantidad',
    'average_price': 'Precio Medio',
    'delete_now': 'Eliminar Ahora',
    'cannot_be_undone': 'Esta acción no se puede deshacer.',
    'wallet_name': 'Nombre de la Cartera',
    'wallet_name_required': 'El nombre de la cartera es obligatorio.',
    'cnpj_razao_required': 'Identificación fiscal y Razón Social son obligatorios.',
    'optional_note': 'Observación (opcional)',
    'details_placeholder': 'Detalles...',
    'notes_placeholder': 'Notas sobre esta cartera...',
    'edit_transaction': 'Editar Transacción',
    'new_transaction_modal': 'Nueva Transacción',
    'edit_goal': 'Editar Meta',
    'new_goal_modal': 'Nueva Meta',
    'edit_investment': 'Editar Inversión',
    'new_investment_modal': 'Nueva Inversión',
    'edit_wallet': 'Editar Cartera',
    'new_wallet_modal': 'Nueva Cartera',
    'placeholder_emergency_fund': 'Ej: Fondo de emergencia...',
    'placeholder_description_modal': 'Ej: Salario, Mercado...',
    'placeholder_asset': 'Ej: PETR4, AAPL...',
    'placeholder_wallet': 'Ej: Principal, Empresa X...',
    'green': 'Verde',
    'light_green': 'Verde claro',
    'purple': 'Morado',
    'orange': 'Naranja',
    'red_color': 'Rojo',
    'stocks': 'Acciones',
    'fiis': 'FIIs',
    'treasury': 'Tesoro',
    'crypto': 'Cripto',
    'fixed_income': 'Renta Fija',
    'salary': 'Salario',
    'freelance': 'Freelance',
    'rent_received': 'Alquiler recibido',
    'investments_cat': 'Inversiones',
    'gift': 'Regalo',
    'others': 'Otros',
    'food': 'Alimentación',
    'housing': 'Vivienda',
    'transport': 'Transporte',
    'health': 'Salud',
    'gym': 'Gimnasio',
    'leisure': 'Ocio',
    'education': 'Educación',
    'clothing': 'Ropa',
    'services': 'Servicios',
    'subscriptions': 'Suscripciones',
    'extras': 'Extras',
    'etfs': 'ETFs',
    'savings': 'Ahorros',
    'other_assets': 'Otros activos',
    'updated': 'Actualizado',
    'saved': 'Guardado',
    'created': 'Creada',
    'added': 'Añadido',
    'wallet_updated': 'Cartera actualizada',
    'wallet_created': 'Cartera creada',
    'wallet_deleted': 'Cartera eliminada',
    'transaction_deleted': 'Transacción eliminada',
    'goal_deleted': 'Meta eliminada',
    'investment_deleted': 'Inversión eliminada',
    'bulk_deleted': 'transacciones eliminadas',
    'wallet_changed': 'Cartera cambiada',
    'min_wallet_warning': 'Debes tener al menos una cartera.',
    'default_wallet_name': 'Mi Cartera',
    'default_wallet_desc': 'Mi cuenta principal',
    'default_wallet_created': 'Cartera predeterminada creada',
    'import_success': '¡transacciones importadas!',
    'export_success': '¡CSV exportado!',
    'select_file': 'Seleccionar Archivo',
    'click_or_drag_csv': 'Haga clic aquí o arrastre el archivo CSV',
    'supported_formats': 'Formatos soportados: .csv',
    'categorizing_ai': 'Categorizando transacciones con IA...',
    'csv_date': 'Fecha',
    'csv_description': 'Descripción',
    'csv_value': 'Valor',
    'csv_back': 'Volver y cambiar archivo',
    'imported_via_csv': 'Importado vía CSV',
    'csv_transaction_fallback': 'Transacción',
    'unnamed_user': 'Usuario',
    'at_least_one_wallet': 'Necesitas al menos una cartera.',
    'wallet': 'Cartera',
    'custom': 'Personalizado',
    'ready': 'Pronto',
    'pref_footer': 'Los cambios de tema se aplican instantáneamente al guardar.',
    'forgot_password': '¿Olvidó su contraseña?',
    'back_to_login': 'Volver al inicio',
    'logout_confirm': '¿Desea cerrar su sesión?',
    'logout_confirm_desc': 'Deberá iniciar sesión nuevamente para acceder a sus datos.',
    'reset_email_sent': '¡Correo de restablecimiento enviado! Revisa tu bandeja de entrada.',
    'reset_email_err': 'Error al enviar el correo. Inténtalo más tarde.',
    'yes': 'Sí',
    'no': 'No',
    'saving': 'Guardando...',
    'sending': 'Enviando...',
    'security_footer_info': 'Tu cuenta está protegida por Firebase Security. Las comunicaciones están cifradas y el acceso está autenticado siguiendo los estándares de seguridad globales.',
    'push_notif_sub': 'Recibe alertas sobre metas y plazos en tu dispositivo.',
    'email_notif_sub': 'Informes semanais y alertas importantes en tu correo electrónico.',
    'notif_tip': 'Puedes silenciar notificaciones individuales en los ajustes de cada cartera.',
    'all': 'Todo',
    'incomes': 'Ingresos',
    'expenses': 'Gastos',
    'monthly_yield': 'Rentabilidad Mensual',
    'yield_calculation_info': 'Al cambiar, el valor total se ajustará proporcionalmente.',
    'planning': 'Planeamiento',
    'shopping_list': 'Lista de Compras',
    'fixed_expenses': 'Gastos Fijos',
    'add_item': 'Agregar Item',
    'priority': 'Prioridad',
    'low': 'Baja',
    'medium': 'Media',
    'high': 'Alta',
    'committed_salary': 'Salario Comprometido',
    'total_fixed': 'Total Fijo',
    'due_day': 'Día de Vencimiento',
    'estimated_price': 'Precio Estimado',
    'total_estimated': 'Total Estimado',
    'planning_desc': 'Organice su futuro financiero y compromisos mensuales.',
    'income_basis': 'Basado en ganancias mensuales:',
    'high_commitment_warning': 'Atención: Gran parte de sus ingresos está comprometida.',
    'item_name': 'Artículo...',
    'price_short': '$',
    'no_items': 'Su lista de compras está vacía.',
    'expense_name': 'Nombre',
    'day_short': 'DÍA',
    'fixed_recurrent': 'Recurrencia Mensual',
    'no_fixed_expenses': 'Ningún gasto fijo registrado.',
    'short_warning': '¡Alto!',
    'delete_selected': 'Eliminar seleccionados',
    'cancel_selection': 'Cancelar selección',
    'complete_registration': 'Termine su registro',
    'verify_account': 'Verifique su cuenta',
    'account_verified': 'Cuenta verificada',
    'birth_date': 'Fecha de Nacimiento',
    'gender': 'Género',
    'city': 'Ciudad',
    'select': 'Seleccionar',
    'male': 'Masculino',
    'female': 'Femenino',
    'other': 'Otro',
    'prefer_not_to_say': 'Prefiero no decir',
    'city_placeholder': 'Ej: Madrid',
    'country': 'País',
    'country_placeholder': 'Ej: España',
    'monthly_income': 'Ingresos Mensuales',
    'income_info_desc': 'Usado para cálculos de planificación financiera.'
  }
};

const PreferencesContext = createContext<PreferencesContextType | undefined>(undefined);

export function PreferencesProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>((localStorage.getItem('app-language') as Language) || 'pt-BR');
  const [currency, setCurrencyState] = useState<Currency>((localStorage.getItem('app-currency') as Currency) || 'BRL');
  const [themeMode, setThemeModeState] = useState<ThemeMode>('auto');
  const [isDark, setIsDark] = useState(false);
  const [showBalances, setShowBalancesState] = useState<boolean>(() => {
    const val = localStorage.getItem('app-show-balances');
    return val !== 'false';
  });

  useEffect(() => {
    const applyTheme = () => {
      let dark = window.matchMedia('(prefers-color-scheme: dark)').matches;
      
      setIsDark(dark);
      if (dark) {
        document.documentElement.classList.add('dark');
        document.documentElement.classList.remove('light');
        document.body.classList.add('dark');
        document.body.classList.remove('light');
      } else {
        document.documentElement.classList.remove('dark');
        document.documentElement.classList.add('light');
        document.body.classList.remove('dark');
        document.body.classList.add('light');
      }
    };

    applyTheme();

    const mediaQuery = window.matchMedia('(prefers-color-scheme: dark)');
    const handleChange = () => {
      applyTheme();
    };

    mediaQuery.addEventListener('change', handleChange);
    return () => mediaQuery.removeEventListener('change', handleChange);
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
  };

  const setCurrency = (curr: Currency) => {
    setCurrencyState(curr);
    localStorage.setItem('app-currency', curr);
  };

  const setThemeMode = (mode: ThemeMode) => {
    setThemeModeState('auto');
    localStorage.setItem('app-theme-mode', 'auto');
  };

  const setShowBalances = (show: boolean) => {
    setShowBalancesState(show);
    localStorage.setItem('app-show-balances', String(show));
  };

  const formatCurrency = (value: number) => {
    const locales: Record<Currency, string> = {
      BRL: 'pt-BR',
      USD: 'en-US',
      EUR: 'de-DE'
    };
    const codes: Record<Currency, string> = {
      BRL: 'BRL',
      USD: 'USD',
      EUR: 'EUR'
    };

    return new Intl.NumberFormat(locales[currency], {
      style: 'currency',
      currency: codes[currency]
    }).format(value);
  };

  const t = (key: string, replacements?: Record<string, string | number>) => {
    let str = translations[language][key] || key;
    if (replacements) {
      Object.entries(replacements).forEach(([k, v]) => {
        str = str.replace(`{{${k}}}`, String(v));
      });
    }
    return str;
  };

  return (
    <PreferencesContext.Provider value={{ 
      language, currency, themeMode, isDark, showBalances,
      setLanguage, setCurrency, setThemeMode, setShowBalances,
      formatCurrency, t
    }}>
      {children}
    </PreferencesContext.Provider>
  );
}

export function usePreferences() {
  const context = useContext(PreferencesContext);
  if (context === undefined) {
    throw new Error('usePreferences must be used within a PreferencesProvider');
  }
  return context;
}
